#! /bin/sh

# Autostart
sxhkd &
nitrogen --restore &
xrandr --dpi 192
picom &
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap		28

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

